# Generated by Django 2.0.7 on 2018-07-16 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_addr', models.EmailField(blank=True, max_length=70, null=True)),
                ('register_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
